import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "body-md": ["Manrope"],
        "display-lg-mobile": ["Inter"],
        "body-lg": ["Manrope"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Manrope"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      },
      spacing: {
        "base": "8px",
        "section-gap": "80px",
        "container-padding-desktop": "32px",
        "gutter": "24px",
        "container-padding-mobile": "20px"
      },
      colors: {
        "primary-fixed-dim": "#d8b9ff",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#5e4200",
        "primary-fixed": "#eddcff",
        "error-container": "#ffdad6",
        "inverse-primary": "#d8b9ff",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "tertiary": "#242424",
        "secondary-fixed-dim": "#f9bc45",
        "outline-variant": "#cdc3d4",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#725000",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed": "#e5e2e1",
        "surface-container": "#edeeef",
        "primary-container": "#4e158f",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-container": "#bc8cff",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#a4a3a2",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#5c289d",
        "surface-dim": "#d9dadb",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        "on-secondary-fixed": "#271900",
        "on-primary-fixed": "#290055",
        "on-surface": "#191c1d",
        "outline": "#7c7483",
        "on-error-container": "#93000a",
        "surface-container-high": "#e7e8e9",
        "secondary-container": "#ffc24a",
        "tertiary-container": "#3a3939",
        "surface-tint": "#7543b7",
        "secondary-fixed": "#ffdea8",
        "on-surface-variant": "#4b4452",
        "surface": "#f8f9fa",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "progress-fill": {
          "0%": { width: "0%" },
          "100%": { width: "var(--progress-width)" },
        },
        "count-up": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "progress-fill": "progress-fill 1.5s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
